// Lokales Preview des neuen 6-seitigen Mietvertrags.
// Run: npx tsx scripts/preview-contract.ts
import { writeFileSync } from "fs";
import { generateContractPdf } from "../src/lib/contract-pdf";
import type { Contract, Customer, Organization, Vehicle } from "../src/lib/types";
import type { VehicleTire } from "../src/lib/tires";

const org: Organization = {
  id: "org-1",
  name: "Eazycar GmbH",
  street: "Eversbuschstraße 12",
  zip: "80999",
  city: "München",
  phone: "+49 89 12345678",
  email: "info@eazycar.de",
  tax_number: "DE123456789",
  processing_fee: 25,
  iban: "DE89 3704 0044 0532 0130 00",
  bic: "COBADEFFXXX",
  account_holder: "EazyCar GmbH",
  kleinunternehmer: false,
  invoice_seq: 0,
  slug: "eazycar",
  inbound_email: null,
  sender_email: null,
  sender_name: null,
  email_automation_enabled: false,
  lexoffice_enabled: false,
  credit_provider: null,
  credit_api_url: null,
  email_provider: "resend",
  email_domain: null,
  email_domain_id: null,
  email_domain_status: "none",
  email_dns_records: null,
  contract_email_subject: null,
  contract_email_body: null,
  echoes_account_id: null,
  echoes_enabled: false,
  rental_terms: null,
  logo_path: null,
  landlord_signature_data: null,
  landlord_signature_name: null,
  created_at: new Date().toISOString(),
};

const customer: Customer = {
  id: "cust-1",
  org_id: org.id,
  customer_type: "privat",
  company_name: null,
  legal_form: null,
  salutation: "Herr",
  title: null,
  first_name: "Hall Construction",
  last_name: "& Service B.V.",
  birthday: null,
  street: "Spekhofstraat",
  house_nr: "24",
  zip: "6466",
  city: "LZ Kerkrade",
  country: "NL",
  email: "hallconstructionbv@gmail.com",
  phone: "+4915159075080",
  license_nr: "J38000A6184",
  license_class: "B",
  license_expiry: null,
  id_card_nr: "L7MJ90G0K",
  license_photo_path: null,
  id_card_photo_path: null,
  license_photo_back_path: null,
  id_card_photo_back_path: null,
  marketing_opt_in: false,
  consent_at: null,
  consent_source: null,
  credit_score: null,
  credit_rating: null,
  credit_decision: null,
  credit_provider: null,
  credit_checked_at: null,
  credit_consent: false,
  credit_raw: null,
  notes: null,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

const vehicle: Vehicle = {
  id: "veh-1",
  org_id: org.id,
  plate: "EU-ML",
  vehicle_type: "Audi A6 Avant",
  color: "Gletscherweiß",
  first_registration: null,
  decommission_date: null,
  decommission_reminded: false,
  disable_auto_decommission: false,
  registration_doc_path: null,
  shopify_product_id: null,
  pickup_location: null,
  return_location: null,
  internal_return_at: null,
  internal_return_note: null,
  extra_km_price: 0.49,
  manufacturer: "Audi",
  model: "A6 Avant EU-ML Gletscherweiß",
  power_ps: 367,
  fuel_type: "Benzin",
  transmission: "Automatik",
  doors: "5",
  seats: 5,
  luggage: 5,
  body_type: "Kombi",
  fin_number: "WAUZZZFN9TN018117",
  category: "Premium",
  hsn: null,
  tsn: null,
  displacement_ccm: null,
  co2_combined: null,
  emission_class: null,
  weight_empty: null,
  weight_max: null,
  zb2_number: null,
  next_hu: null,
  registration_data: null,
  insurer: null,
  policy_number: null,
  insurance_valid_until: null,
  insurance_policy_path: null,
  insurance_card_path: null,
  available_from: null,
  km_at_intake: null,
  max_km_total: null,
  inclusive_km_month: 3000,
  daily_rate: 99.0,
  base_daily_rate: 99.0,
  weekly_rate: null,
  monthly_rate: null,
  deposit: 2000,
  cost_daily: null,
  cost_monthly: null,
  target_daily_rate: null,
  onetime_cost_supplier: null,
  onetime_cost_pickup: null,
  onetime_cost_return: null,
  leasing_doc_path: null,
  accessories: null,
  status: "aktiv",
  incomplete: false,
  successor_status: null,
  successor_vehicle_id: null,
  successor_contract_id: null,
  echoes_device_id: null,
  last_gps_lat: null,
  last_gps_lng: null,
  last_gps_update: null,
  lexoffice_product_id: null,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

const contract: Contract = {
  id: "c-1",
  org_id: org.id,
  contract_nr: "EU-ML",
  vehicle_id: vehicle.id,
  customer_id: customer.id,
  plate: "EU-ML",
  vehicle_type: "Audi A6 Avant",
  renter_name: "Hall Construction & Service B.V.",
  renter_email: customer.email,
  renter_phone: customer.phone,
  renter_address: "Spekhofstraat 24, 6466 LZ Kerkrade",
  renter_birthday: null,
  renter_license_nr: customer.license_nr,
  renter_license_class: "B",
  renter_license_expiry: null,
  pickup_date: "2026-04-14",
  pickup_time: "13:30",
  return_date: "2026-10-13",
  return_time: "13:30",
  actual_return_date: null,
  daily_rate: 99.0,
  total_amount: 1600.0,
  deposit: 2000.0,
  km_pickup: 100,
  km_return: null,
  km_limit: 18000,
  extra_km_cost: null,
  actual_days: null,
  actual_km_allowed: null,
  km_driven: null,
  km_excess: null,
  status: "aktiv",
  lexoffice_invoice_id: null,
  is_activated: false,
  activated_at: null,
  deposit_invoice_id: null,
  payment_status: null,
  paid_at: null,
  partner_id: null,
  partner_purchase_price: null,
  partner_selling_price: null,
  partner_commission: null,
  signed_contract_path: null,
  signature_data: null,
  signed_at: null,
  signed_ip: null,
  checkin_step: 0,
  checkout_step: 0,
  fuel_level_pickup: "1/8 Füllstand",
  fuel_level_return: null,
  contract_pdf_path: null,
  pickup_photos: [],
  return_photos: [],
  notes: null,
  payment_method: "bank_transfer",
  insurance_type: "full",
  insurance_deductible: 2500,
  special_terms: "Auslandsfahrten sind nur innerhalb des DACH-Verbandes zulässig.",
  delivery_cost: 0,
  pickup_cost: 0,
  driver2_name: null,
  driver2_license: null,
  damages_at_handover: "Keine/Neuwagen",
  keys_count: 1,
  selected_special_terms: [],
  custom_special_terms: null,
  risk_consent: false,
  risk_level: null,
  risk_score: null,
  risk_summary: null,
  risk_factors: null,
  risk_checked_at: null,
  risk_override_by: null,
  risk_override_at: null,
  risk_override_reason: null,
  email_sent_at: null,
  email_sent_to: null,
  damage_comparison: null,
  damage_comparison_at: null,
  has_new_damage: null,
  damage_max_severity: null,
  condition_at_return: null,
  handover_sig_lessor_pickup: null,
  handover_sig_renter_pickup: null,
  handover_sig_lessor_return: null,
  handover_sig_renter_return: null,
  handover_protocol_pickup_path: null,
  handover_protocol_return_path: null,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

const tire: VehicleTire = {
  id: "t-1",
  vehicle_id: vehicle.id,
  org_id: org.id,
  type: "summer",
  brand: "Pirelli",
  model: "P Zero",
  size: "255/40 R20",
  dot_number: null,
  tread_depth_fl: 6.5,
  tread_depth_fr: 6.5,
  tread_depth_rl: 7.0,
  tread_depth_rr: 7.0,
  km_at_mount: null,
  mounted_at: null,
  dismounted_at: null,
  is_current: true,
  storage_location: null,
  condition: "good",
  notes: null,
  created_at: new Date().toISOString(),
};

const sampleTerms = [
  {
    id: "t1",
    org_id: org.id,
    title: "Nichtraucherfahrzeug",
    text: "Das Fahrzeug ist ein Nichtraucherfahrzeug. Bei Zuwiderhandlung gegen das Rauchverbot berechnen wir pauschal 250€ für eine Innenreinigung inkl. erforderlicher Ozonbehandlung.",
    category: "general" as const,
    sort_order: 10,
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "t2",
    org_id: org.id,
    title: "Auslandsfahrten DACH",
    text: "Auslandsfahrten sind nur innerhalb des DACH-Verbandes zulässig.",
    category: "international" as const,
    sort_order: 50,
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "t3",
    org_id: org.id,
    title: "Launch-Control",
    text: "Mit der Verwendung von Launch-Control erlischt die Garantie und der Mieter haftet in vollem Umfang.",
    category: "sportscars" as const,
    sort_order: 90,
    active: true,
    created_at: new Date().toISOString(),
  },
];

(async () => {
  const buf = await generateContractPdf({
    org,
    contract: {
      ...contract,
      custom_special_terms:
        "Fahrzeug bitte nur an Premium-Tankstellen tanken.\nKein Carsharing-Subleasing.",
      damages_at_handover: "Steinschlag rechte Seitenscheibe, Kratzer linke Heckstoßstange",
    },
    customer,
    vehicle,
    tires: tire,
    logoPngBase64: null,
    specialTerms: sampleTerms,
  });
  writeFileSync("/tmp/preview-contract.pdf", buf);
  console.log("→ /tmp/preview-contract.pdf");
})();
