// Lokales Preview: rendert die 3 PDFs mit Testdaten nach /tmp/.
// Run: npx tsx scripts/preview-pdfs.ts
import { writeFileSync } from "fs";
import {
  generateInvoicePdf,
  generateLetterPdf,
  generateQuestionnairePdf,
} from "../src/lib/pdf-generator";
import type { Contract, Organization, Ticket } from "../src/lib/types";

const org: Organization = {
  id: "00000000",
  name: "Stadtflotte München GmbH",
  street: "Bayerstraße 12",
  zip: "80335",
  city: "München",
  phone: "+49 89 12345678",
  email: "kontakt@stadtflotte.de",
  tax_number: "DE123456789",
  processing_fee: 25,
  iban: "DE89 3704 0044 0532 0130 00",
  bic: "COBADEFFXXX",
  account_holder: "Stadtflotte München GmbH",
  kleinunternehmer: false,
  invoice_seq: 0,
  slug: "stadtflotte",
  inbound_email: "stadtflotte@knoellchen-pilot.de",
  sender_email: null,
  sender_name: null,
  email_automation_enabled: true,
  lexoffice_enabled: false,
  credit_provider: null,
  credit_api_url: null,
  email_provider: "resend",
  email_domain: null,
  email_domain_id: null,
  email_domain_status: "none",
  email_dns_records: null,
  contract_email_subject: null,
  contract_email_body: null,
  echoes_account_id: null,
  echoes_enabled: false,
  rental_terms: null,
  logo_path: null,
  landlord_signature_data: null,
  landlord_signature_name: null,
  created_at: new Date().toISOString(),
};

const ticket: Ticket = {
  id: "t1",
  org_id: "00000000",
  ticket_nr: "KP-253494",
  invoice_nr: "RG-2026-00042",
  status: "zugeordnet",
  plate: "M-AV 5678",
  vehicle_type: "VW Polo",
  offense: "Geschwindigkeitsüberschreitung außerorts um 21 km/h",
  offense_details: "71 km/h bei zulässigen 50 km/h (nach Toleranzabzug)",
  location: "Landsberger Straße 155, 80339 München",
  offense_date: "2026-04-21",
  offense_time: "14:38",
  authority: "Polizeipräsidium München",
  reference_nr: "PP-VK-2026-04-29381",
  fine_amount: 115.0,
  points: 1,
  deadline: "2026-05-06",
  ai_confidence: 0.98,
  ai_raw_response: null,
  booking_id: null,
  contract_id: "c1",
  renter_name: "Lukas Becker",
  renter_email: "lukas.becker@example.de",
  processing_fee: 29.75,
  charge_fine: true,
  charge_fee: true,
  fee_net: 25,
  fee_vat: 4.75,
  fee_gross: 29.75,
  total_charge: 144.75,
  lexoffice_invoice_id: null,
  paid: false,
  reminder_level: 0,
  upload_path: null,
  letter_path: null,
  invoice_path: null,
  questionnaire_path: null,
  letter_sent: false,
  authority_sent: false,
  inbound_email_id: null,
  letter_sent_at: null,
  letter_sent_to: null,
  authority_sent_at: null,
  authority_sent_to: null,
  authority_email: null,
  source: "upload",
  notes: null,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

const contract: Contract = {
  id: "c1",
  org_id: "00000000",
  contract_nr: "MV-2026-0042",
  vehicle_id: null,
  customer_id: null,
  plate: "M-AV 5678",
  vehicle_type: "VW Polo",
  renter_name: "Lukas Becker",
  renter_email: "lukas.becker@example.de",
  renter_phone: "+49 175 8765432",
  renter_address: "Sonnenstraße 24, 80331 München",
  renter_birthday: "1992-09-15",
  renter_license_nr: "B 8765432109",
  renter_license_class: "B",
  renter_license_expiry: "2025-06-12",
  pickup_date: "2026-04-20",
  pickup_time: "09:30",
  return_date: "2026-04-23",
  return_time: "18:00",
  actual_return_date: null,
  daily_rate: 49.0,
  total_amount: 147.0,
  deposit: 250.0,
  km_pickup: 24812,
  km_return: null,
  km_limit: null,
  extra_km_cost: null,
  actual_days: null,
  actual_km_allowed: null,
  km_driven: null,
  km_excess: null,
  status: "aktiv",
  lexoffice_invoice_id: null,
  is_activated: false,
  activated_at: null,
  deposit_invoice_id: null,
  payment_status: null,
  paid_at: null,
  partner_id: null,
  partner_purchase_price: null,
  partner_selling_price: null,
  partner_commission: null,
  signed_contract_path: null,
  signature_data: null,
  signed_at: null,
  signed_ip: null,
  checkin_step: 0,
  checkout_step: 0,
  fuel_level_pickup: null,
  fuel_level_return: null,
  contract_pdf_path: null,
  pickup_photos: [],
  return_photos: [],
  notes: null,
  payment_method: null,
  insurance_type: null,
  insurance_deductible: null,
  special_terms: null,
  delivery_cost: null,
  pickup_cost: null,
  driver2_name: null,
  driver2_license: null,
  damages_at_handover: null,
  keys_count: null,
  selected_special_terms: [],
  custom_special_terms: null,
  risk_consent: false,
  risk_level: null,
  risk_score: null,
  risk_summary: null,
  risk_factors: null,
  risk_checked_at: null,
  risk_override_by: null,
  risk_override_at: null,
  risk_override_reason: null,
  email_sent_at: null,
  email_sent_to: null,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

writeFileSync("/tmp/preview-letter.pdf", Buffer.from(generateLetterPdf(org, ticket, contract)));
writeFileSync("/tmp/preview-invoice.pdf", Buffer.from(generateInvoicePdf(org, ticket, contract)));
writeFileSync("/tmp/preview-questionnaire.pdf", Buffer.from(generateQuestionnairePdf(org, ticket, contract)));
console.log("✓ /tmp/preview-letter.pdf");
console.log("✓ /tmp/preview-invoice.pdf");
console.log("✓ /tmp/preview-questionnaire.pdf");
